language: r
sudo: required
r:
 - release 
 - devel
r_check_args: --as-cran 
warnings_are_errors: true

before_install:
    - export DISPLAY=:99.0

after_success:
  - Rscript -e 'library("covr");codecov(type="test")'
