#+BEGIN_HTML
<a href="http://cran.rstudio.com/web/packages/LMMstar/index.html"><img src="http://www.r-pkg.org/badges/version/LMMstar"></a>
<a href="http://cranlogs.r-pkg.org/downloads/total/last-month/LMMstar"><img src="http://cranlogs.r-pkg.org/badges/LMMstar"></a>
<a href="https://ci.appveyor.com/project/bozenne/LMMstar"><img src="https://ci.appveyor.com/api/projects/status/github/bozenne/LMMstar?svg=true" alt="Build status"></a>
<a href="https://github.com/bozenne/LMMstar/actions"><img src="https://github.com/bozenne/LMMstar/workflows/r/badge.svg" alt="Build status"></a>
<a href="http://www.gnu.org/licenses/gpl-3.0.html"><img src="https://img.shields.io/badge/License-GPLv3-blue.svg" alt="License"></a>
#+END_HTML

#+BEGIN_SRC R :exports none :results output :session *R* :cache no
options(width = 100)
#+END_SRC

#+RESULTS:

* LMMstar

*LMMstar* is companion R package for the course "Statistical analysis
of correlated and repeated measurements for health science
researchers" taught by the section of Biostatistics of the University
of Copenhagen. It provides functions for computing summary statistics
and obtainign graphical displays of longitudinal data, as well as for
statistical modeling and statistical inference using mixed models.

This package builds on existing methods and softwares, e.g.:
- =emmeans= for computing marginal means
- =lava= for simulating data
- =multcomp= for adjusting for multiple comparisons
- =nlme= for fitting mixed model
The main feature of the package is to provide a convenient user
interface.

* Installation

To install the package, you will need:
- 1. :: A fairly recent R version (>=4.0.0). You can check that using:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
paste0(R.Version()[c("major","minor")], collapse = ".")
#+END_SRC

#+RESULTS:
: [1] "4.1.1"

- 2. :: Rtools (only for windows users!). To check whether Rtools is
        installed, you can first install the R package =pkgbuild=:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
install.packages("pkgbuild")
#+END_SRC

#+RESULTS:
#+begin_example
Installing package into 'C:/Users/hpl802/Documents/R/win-library/4.1'
(as 'lib' is unspecified)
trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.1/pkgbuild_1.2.0.zip'
Content type 'application/zip' length 141813 bytes (138 KB)
downloaded 138 KB

package 'pkgbuild' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\hpl802\AppData\Local\Temp\RtmpquounF\downloaded_packages
#+end_example

and then run:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
pkgbuild::find_rtools()
#+END_SRC

#+RESULTS:
: [1] TRUE
It should say =TRUE=. Otherwise go to
https://cran.r-project.org/bin/windows/Rtools/, download and run the
installer. Then try to run again =pkgbuild::find_rtools()=.

- 3. :: The library =remotes= that you can install running:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
install.packages("remotes")
#+END_SRC

#+RESULTS:
#+begin_example
Installing package into 'C:/Users/hpl802/Documents/R/win-library/4.1'
(as 'lib' is unspecified)
trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.1/remotes_2.4.0.zip'
Content type 'application/zip' length 395672 bytes (386 KB)
downloaded 386 KB

package 'remotes' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\hpl802\AppData\Local\Temp\Rtmp44ARJ0\downloaded_packages
#+end_example


- 4. :: Run the following line of code to download and install the package:
#+BEGIN_SRC R :exports both :eval never
remotes::install_github("bozenne/LMMstar")
#+END_SRC

Note: you can check that the package has been correctly installed by running
the following lines of code:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
library(LMMstar)
set.seed(10)
dW <- sampleRem(10, n.times = 3)
head(round(dW,3))
#+END_SRC

#+RESULTS:
: Indlæser krævet pakke: nlme
: LMMstar version 0.2.6
:   id X1 X2 X3 X4 X5     X6     X7    X8    X9    X10     Y1     Y2     Y3
: 1  1  0  0  1  0  0 -0.456 -1.004 0.475 0.167 -1.263 -2.048  1.220  2.599
: 2  2  0  0  1  1  3 -0.830  4.104 0.343 1.024 -0.953  4.982  3.431  6.831
: 3  3  1  1  2  1  0  0.340  6.413 3.669 0.045  0.326  9.530 11.410 12.638
: 4  4  1  0  1  1  2  1.066  1.517 0.065 1.522 -1.172  6.212  7.113  7.936
: 5  5  1  0  2  1  1  1.216  2.359 1.942 0.444 -0.938  6.108  6.590  8.388
: 6  6  1  0  2  1  1  0.736 -2.707 2.465 2.753 -0.123  1.838  3.548  3.622

* Export citation

#+BEGIN_SRC R :exports both :results output :session *R* :cache no
citation("LMMstar")
#+END_SRC

#+RESULTS:
#+begin_example

To cite the 'LMMstar' package in publications use the following text:

  Brice Ozenne and Julie Forman (2021). LMMstar: Repeated measurement models for discrete
  times. R package version 0.2.6.

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {LMMstar: Repeated measurement models for discrete times},
    author = {Brice Ozenne and Julie Forman},
    year = {2021},
    note = {R package version 0.2.6},
  }
#+end_example

* Functionalities
See the vignette "Overview of the package LMMstar" in [[./vignettes/overview.pdf]]


