#+BEGIN_HTML
<a href="http://cran.rstudio.com/web/packages/LMMstar/index.html"><img src="http://www.r-pkg.org/badges/version/LMMstar"></a>
<a href="http://cranlogs.r-pkg.org/downloads/total/last-month/LMMstar"><img src="http://cranlogs.r-pkg.org/badges/LMMstar"></a>
<a href="https://ci.appveyor.com/project/bozenne/LMMstar"><img src="https://ci.appveyor.com/api/projects/status/github/bozenne/LMMstar?svg=true" alt="Build status"></a>
<a href="https://github.com/bozenne/LMMstar/actions"><img src="https://github.com/bozenne/LMMstar/workflows/r/badge.svg" alt="Build status"></a>
<a href="http://www.gnu.org/licenses/gpl-3.0.html"><img src="https://img.shields.io/badge/License-GPLv3-blue.svg" alt="License"></a>
#+END_HTML

#+BEGIN_SRC R :exports none :results output :session *R* :cache no
options(width = 100)
#+END_SRC

#+RESULTS:

* LMMstar: Repeated Measurement Models for Discrete Times

*LMMstar* stands for Linear Mixed Models - statistical analysis in
R. It is companion R package for the course "Statistical analysis of
correlated and repeated measurements for health science researchers"
taught by the section of Biostatistics of the University of
Copenhagen. It provides functions for computing summary statistics and
obtaining graphical displays of longitudinal data, as well as for
statistical modeling and statistical inference using mixed models. In
particular, it implements linear mixed models where the model for the
variance-covariance of the residuals is specified via patterns
(compound symmetry, toeplitz, unstructured, ...), possibly stratified
on a categorical variable. Statistical uncertainty for mean, variance,
and correlation parameters is performed based on the observed
information. Statistical testing can be performed for arbitrary linear
or non-linear combination(s) of model coefficients. For linear
combinations, a Satterthwaite approximation of the degrees of freedom
is available.  Normalized residuals are provided to assess model
misspecification. Predictions can be computed conditional to
covariates only or also to outcome values.

This package builds on existing software:
- =lava= for simulating data
- =multcomp= for adjusting for multiple comparisons
- =ggplot2= for graphical displays

** Installation

You can download the latest stable version on =CRAN= using:
#+BEGIN_SRC R :exports both :eval never
install.packages("LMMstar")
#+END_SRC

or download the development version from =GitHub=:
#+BEGIN_SRC R :exports both :eval never
library(remotes)
install_github("bozenne/LMMstar")
#+END_SRC

For the later you will need a fairly recent R version (>=4.0.0) and,
for windows users, [[https://cran.r-project.org/bin/windows/Rtools/][Rtools]]. You can check both using:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
paste0(R.Version()[c("major","minor")], collapse = ".")
pkgbuild::find_rtools()
#+END_SRC

#+RESULTS:
: [1] "4.1.1"
: [1] TRUE

** Export citation

#+BEGIN_SRC R :exports both :results output :session *R* :cache no
citation("LMMstar")
#+END_SRC

#+RESULTS:
#+begin_example

To cite the 'LMMstar' package in publications use the following text:

  Brice Ozenne and Julie Forman (2021). LMMstar: Repeated measurement models for discrete
  times. R package version 0.2.6.

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {LMMstar: Repeated measurement models for discrete times},
    author = {Brice Ozenne and Julie Forman},
    year = {2021},
    note = {R package version 0.2.6},
  }
#+end_example

** Functionalities
See the vignette "Overview of the package LMMstar" in [[./vignettes/overview.pdf]]

  
