#+BEGIN_HTML
<a href="https://travis-ci.org/bozenne/handrem"><img src="https://travis-ci.org/bozenne/handrem.svg?branch=master"></a>
<a href="https://ci.appveyor.com/project/bozenne/handrem"><img src="https://ci.appveyor.com/api/projects/status/github/bozenne/handrem?svg=true" alt="Build status"></a>
<a href="http://www.gnu.org/licenses/gpl-3.0.html"><img src="https://img.shields.io/badge/License-GPLv3-blue.svg" alt="License"></a>
#+END_HTML

* handremn

*handrem* is companion R package for the course "Statistical analysis
of correlated and repeated measurements for health science
researchers" taught by the section of Biostatistics of the University
of Copenhagen. It provides functions for computing summary statistics
and obtainign graphical displays of longitudinal data, as well as for
statistical modeling and statistical inference using mixed models.

This package does not implement any new methods. Instead it builds on
existing methods and softwares, e.g.: 
- =nlme= for fitting mixed model
The main feature of the package is to provide a convenient user
interface.

* Installation

The easiest way to install this R package is to first install the
library =devtools=:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
install.packages("devtools")
#+END_SRC
and then run the following R code:
#+BEGIN_SRC R :exports both :eval never
devtools::install_github("bozenne/BuyseTest")
#+END_SRC

* Functionalities 

Load the package:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
library(handrem)
#+END_SRC

#+RESULTS:
: handrem version 0.1.0


[optional] Simulate some data using the =lava= package:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
library(lava)
m <- lvm(c(Y1,Y2,Y3,Y4) ~ age + gender)
categorical(m, labels = c("male","female")) <- ~gender
transform(m, id~gender) <- function(x){1:NROW(x)}
distribution(m, ~age) <- gaussian.lvm(mean = 50, sd = 10)

set.seed(10)
dW <- lava::sim(m, 1e2)
head(dW)
#+END_SRC

#+RESULTS:
:         Y1       Y2       Y3       Y4      age gender id
: 1 58.71350 57.93295 59.91026 60.19730 58.69475   male  1
: 2 44.01565 44.61928 44.53078 44.79031 43.19990 female  2
: 3 51.36081 51.69220 54.12242 52.10146 51.73215 female  3
: 4 48.80645 50.11719 50.27767 50.19797 48.40562 female  4
: 5 58.22954 57.30178 56.85418 58.06038 57.93499   male  5
: 6 67.33330 67.50668 67.43933 67.26626 66.94350   male  6

and also create the long formal version:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
name.varying <- paste0("Y",1:4)
dL <- reshape(dW, direction  = "long",
              idvar = c("id","age","gender"),
              varying = name.varying,
              v.names = "Y",
              timevar = "visit")
rownames(dL) <- NULL
dL$visit <- factor(dL$visit,
                   levels = 1:length(name.varying),
                   labels = name.varying)
head(dL)
#+END_SRC

#+RESULTS:
:        age gender id visit        Y
: 1 58.69475   male  1    Y1 58.71350
: 2 43.19990 female  2    Y1 44.01565
: 3 51.73215 female  3    Y1 51.36081
: 4 48.40562 female  4    Y1 48.80645
: 5 57.93499   male  5    Y1 58.22954
: 6 66.94350   male  6    Y1 67.33330

Descriptive statistics using the =procSummary= function:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
procSummary(Y1+Y2 ~ gender, data = dW)
#+END_SRC

#+RESULTS:
:   outcome gender observed missing     mean        sd      min   median      max
: 1      Y1   male       58       0 51.28103 11.734087 24.92946 52.99877 84.58108
: 2      Y1 female       42       0 50.56145  9.821041 26.12782 50.09818 69.96275
: 3      Y2   male       58       0 51.41278 11.748875 24.71661 53.01328 85.93246
: 4      Y2 female       42       0 50.47853 10.081425 25.93735 50.23454 68.98899

Fit a linear mixed model with unstructured covariance matrix:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
e.lmm <- lmm(Y ~ visit + age + gender, covariance = ~visit|id, data = dL)
summary(e.lmm)
#+END_SRC

#+RESULTS:
#+begin_example
Generalized least squares fit by REML
  Model: Y ~ visit + age + gender 
  Data: data 
       AIC      BIC    logLik
  1167.926 1231.547 -567.9628

Correlation Structure: General
 Formula: ~visit.index | id 
 Parameter estimate(s):
 Correlation: 
  1      2      3     
2 -0.051              
3  0.008 -0.131       
4  0.044  0.036 -0.006
Variance function:
 Structure: Different standard deviations per stratum
 Formula: ~1 | visit 
 Parameter estimates:
      Y1       Y2       Y3       Y4 
1.000000 1.032857 1.030398 1.107789 

Coefficients:
                  Value  Std.Error   t-value p-value
(Intercept)  -0.1471751 0.24699398  -0.59587  0.5516
visitY2       0.0415864 0.13898590   0.29921  0.7649
visitY3       0.1653008 0.13485948   1.22573  0.2210
visitY4       0.3353877 0.13762341   2.43700  0.0153
age           0.9998180 0.00436729 228.93345  0.0000
genderfemale  1.0472680 0.09658085  10.84343  0.0000

 Correlation: 
             (Intr) vistY2 vistY3 vistY4 age   
visitY2      -0.273                            
visitY3      -0.265  0.429                     
visitY4      -0.249  0.486  0.448              
age          -0.910  0.000  0.000  0.000       
genderfemale -0.237  0.000  0.000  0.000  0.081

Standardized residuals:
       Min         Q1        Med         Q3        Max 
-2.5176917 -0.7453180  0.0106393  0.7606955  2.5193225 

Residual standard error: 0.9430367 
Degrees of freedom: 400 total; 394 residual
#+end_example

Code used to fit the model
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
cat(attr(e.lmm,"code"))
#+END_SRC

#+RESULTS:
: nlme::gls(model=Y~visit+age+gender,
:     data=data,
:     correlation=nlme::corSymm(form=~visit.index|id),
:     weights=nlme::varIdent(form=~1|visit))

Data used to fit the model
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
head(attr(e.lmm,"data"))
#+END_SRC

#+RESULTS:
:        age gender id visit        Y visit.index
: 1 58.69475   male  1    Y1 58.71350           1
: 2 43.19990 female  2    Y1 44.01565           1
: 3 51.73215 female  3    Y1 51.36081           1
: 4 48.40562 female  4    Y1 48.80645           1
: 5 57.93499   male  5    Y1 58.22954           1
: 6 66.94350   male  6    Y1 67.33330           1

Summary based on the =nlme= package
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
summary(e.lmm)
#+END_SRC

#+RESULTS:
#+begin_example
Generalized least squares fit by REML
  Model: Y ~ visit + age + gender 
  Data: data 
       AIC      BIC    logLik
  1167.926 1231.547 -567.9628

Correlation Structure: General
 Formula: ~visit.index | id 
 Parameter estimate(s):
 Correlation: 
  1      2      3     
2 -0.051              
3  0.008 -0.131       
4  0.044  0.036 -0.006
Variance function:
 Structure: Different standard deviations per stratum
 Formula: ~1 | visit 
 Parameter estimates:
      Y1       Y2       Y3       Y4 
1.000000 1.032857 1.030398 1.107789 

Coefficients:
                  Value  Std.Error   t-value p-value
(Intercept)  -0.1471751 0.24699398  -0.59587  0.5516
visitY2       0.0415864 0.13898590   0.29921  0.7649
visitY3       0.1653008 0.13485948   1.22573  0.2210
visitY4       0.3353877 0.13762341   2.43700  0.0153
age           0.9998180 0.00436729 228.93345  0.0000
genderfemale  1.0472680 0.09658085  10.84343  0.0000

 Correlation: 
             (Intr) vistY2 vistY3 vistY4 age   
visitY2      -0.273                            
visitY3      -0.265  0.429                     
visitY4      -0.249  0.486  0.448              
age          -0.910  0.000  0.000  0.000       
genderfemale -0.237  0.000  0.000  0.000  0.081

Standardized residuals:
       Min         Q1        Med         Q3        Max 
-2.5176917 -0.7453180  0.0106393  0.7606955  2.5193225 

Residual standard error: 0.9430367 
Degrees of freedom: 400 total; 394 residual
#+end_example

